import type { ArclumeConfig } from "./config.js";
import type { PatternGroup } from "./ignore-file.js";

export interface ConfigTemplateOpts {
  languages: string[];
  frameworks: string[];
  entryPoints: string[];
}

export function configTemplate(opts: ConfigTemplateOpts): ArclumeConfig {
  return {
    version: "1",
    language: opts.languages,
    framework: opts.frameworks,
    entryPoints: opts.entryPoints,
    graphDepth: 5,
    chunkSize: 512,
    openspec: false,
    contextFile: ".arclume/context.md",
    highWeightPaths: [],
    lowWeightPaths: [],
  };
}

export interface ContextTemplateOpts {
  description: string;
  architecture: string;
  entryPoints: string[];
  decisions: string;
  deemphasize: string;
}

export function contextTemplate(opts: ContextTemplateOpts): string {
  const entryPointsList =
    opts.entryPoints.length > 0
      ? opts.entryPoints.map((ep) => `- \`${ep}\``).join("\n")
      : "- (none specified)";

  return `# Repo Context

## What this is
${opts.description || "[One paragraph description of what this codebase does and why it exists]"}

## Architecture
${opts.architecture || "[Key modules, layers, and how they relate to each other]"}

## Entry Points
${entryPointsList}

## Key Design Decisions
${opts.decisions || "[Why certain approaches were taken — tradeoffs, constraints, historical context]"}

## What to de-emphasize
${opts.deemphasize || "[Generated files, legacy modules, vendored code, areas undergoing rewrite]"}
`;
}

export function ignoreTemplate(groups: PatternGroup[]): string {
  const lines: string[] = ["# .arclumeignore", "# Generated by arclume init", ""];

  for (const group of groups) {
    lines.push(`# ${group.label}`);
    lines.push(...group.patterns);
    lines.push("");
  }

  return lines.join("\n");
}

export function openspecOverviewTemplate(): string {
  return `# Overview

> This file was scaffolded by \`arclume init\`. Edit it to describe your project at a high level.

## Purpose

[What does this system do? What problem does it solve?]

## Key Concepts

[Define the core domain concepts and terminology used in this codebase.]

## System Boundaries

[What is in scope and out of scope for this system?]

## High-Level Architecture

[Describe the major components and how they interact.]
`;
}
